// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17OreGQ7Rmo6_TGpeOUpF4N2fAwTmKwQ',
    appId: '1:916697409220:web:2a11ffb14fadef778c0b91',
    messagingSenderId: '916697409220',
    projectId: 'kayungyun-bfe27',
    authDomain: 'kayungyun-bfe27.firebaseapp.com',
    storageBucket: 'kayungyun-bfe27.firebasestorage.app',
    measurementId: 'G-NSGJ88680L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9T8j48hixEWEKPV_DI3BHHjPyvAPjsQM',
    appId: '1:916697409220:android:aadb5eaad95730e18c0b91',
    messagingSenderId: '916697409220',
    projectId: 'kayungyun-bfe27',
    storageBucket: 'kayungyun-bfe27.firebasestorage.app',
  );
}
